AWSTemplateFormatVersion: 2010-09-09
Resources:
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: [lambda.amazonaws.com]
            Action: ['sts:AssumeRole']
      Path: /
      Policies:
        - PolicyName: logs
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: ['logs:*']
                Resource: 'arn:aws:logs:*:*:*'
        - PolicyName: s3pol
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: ['s3:*']
                Resource: '*'
        - PolicyName: rdspol
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "rds:describe*"
                  - "rds:get*"
                  - "rds:list*"
                Resource: '*'
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      AssumeRolePolicyDocument: !Ref ExecutionRole.Arn
      CodeUri: postgres/
      Handler: pg_healthcheck_lambda.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          ENDPOINT: ""
          DBNAME: ""
          DBPORT:
          MASTERUSER: ""
          MYPASS: ""
          COMNAME: ""
          BUCKET: ""
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /
            Method: get

Globals:
  Function:
    Timeout: 180




Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
