AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  rdsFunction:
    Type: AWS::Serverless::Function
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: [lambda.amazonaws.com]
            Action: ['sts:AssumeRole']
      CodeUri: postgres/
      Handler: pg_healthcheck_lambda.lambda_handler
      Runtime: python3.8
      Timeout: 180
      Events:
        rdsFunction:
          Type: HttpApi
          Properties:
            Path: /
            Method: get
      Policies:
      - Statement:
        - Sid: logsPol
          Effect: Allow
          Action:
          - logs:*
          Resource: '*'
        - Sid: s3Pol
          Effect: Allow
          Action:
          - s3:*
          Resource: '*'
        - Sid: rdsPol
          Effect: Allow
          Action:
          - rds:describe*
          Resource: '*'
        - Sid: stsPol
          Effect: Allow
          Action:
          - sts:getCallerIdentity
          Resource: '*'
      VpcConfig:
        SecurityGroupIds:
          - sg-0765ba559515af3f8
        SubnetIds:
          - subnet-0a34d3dc411a020c9
          - subnet-0e0d5777a50dd7e2e
